"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import type { Episode, Segment } from "@/app/lib/investigation/types";
import { buttonClass, inputClass, LoadState, linkClass, SourceLink, useDataset } from "../shared";

export default function Episodes() {
  const episodes = useDataset<{ episodes: Episode[] }>("episodes");
  const segments = useDataset<{ segments: Segment[] }>("segments");
  if (!episodes.data || !segments.data)
    return (
      <>
        <h1>A story in ten stages.</h1>
        <LoadState
          error={episodes.error || segments.error}
          retry={() => {
            episodes.retry();
            segments.retry();
          }}
        />
      </>
    );
  return <Timeline episodes={episodes.data.episodes} segments={segments.data.segments} />;
}
function Timeline({ episodes, segments }: { episodes: Episode[]; segments: Segment[] }) {
  const [query, setQuery] = useState("");
  const [alarm, setAlarm] = useState(false);
  const [stage, setStage] = useState(0);
  const [limit, setLimit] = useState(20);
  const [selected, setSelected] = useState<number | null>(null);
  const [full, setFull] = useState(false);
  const selectedRef = useRef<HTMLElement>(null);
  const stageRef = useRef<HTMLElement>(null);
  useEffect(() => {
    if (selected !== null) selectedRef.current?.scrollIntoView({ block: "start" });
    else if (stage) stageRef.current?.scrollIntoView({ block: "start" });
  }, [selected, stage]);
  useEffect(() => {
    const update = () => {
      const match = window.location.hash.match(/^#ep-?(\d+)$/);
      const segment = window.location.hash.match(/^#stage(\d+)$/);
      if (match) {
        setSelected(Number(match[1]));
        setQuery("");
        setAlarm(false);
        setStage(0);
      }
      if (segment) {
        setStage(Number(segment[1]));
        setSelected(null);
        setQuery("");
        setAlarm(false);
      }
    };
    update();
    window.addEventListener("hashchange", update);
    return () => window.removeEventListener("hashchange", update);
  }, []);
  const searchable = useMemo(
    () =>
      episodes.map((ep) => ({
        ep,
        text: [
          ep.thinking,
          ep.visible,
          ep.note ?? "",
          ...ep.tools.map((t) => `${t.name} ${t.call_preview} ${t.result_preview}`),
          ...Object.values(ep.artifacts).flat(),
        ]
          .join(" ")
          .toLowerCase(),
      })),
    [episodes],
  );
  const filtered = useMemo(() => {
    const terms = query.toLowerCase().trim().split(/\s+/).filter(Boolean);
    const segment = segments.find((s) => s.id === stage);
    return searchable
      .filter(
        ({ ep, text }) =>
          (!segment || (ep.ep >= segment.ep_start && ep.ep <= segment.ep_end)) &&
          (!alarm || (ep.wobble ?? 0) >= 0.25) &&
          terms.every((term) => text.includes(term)),
      )
      .map(({ ep }) => ep);
  }, [searchable, segments, query, stage, alarm]);
  const focus = episodes.find((ep) => ep.ep === selected);
  function chooseStage(id: number) {
    setStage(id);
    setSelected(null);
    setLimit(20);
    window.history.replaceState(null, "", id ? `#stage${id}` : window.location.pathname);
  }
  function jumpAlarm(direction: number) {
    const alarms = filtered.filter((ep) => (ep.wobble ?? 0) >= 0.25);
    const target =
      direction > 0
        ? alarms.find((ep) => ep.ep > (selected ?? 0))
        : [...alarms].reverse().find((ep) => ep.ep < (selected ?? 704));
    if (target) {
      setSelected(target.ep);
      window.history.replaceState(null, "", `#ep${target.ep}`);
    }
  }
  return (
    <>
      <h1 className="mb-3">A story in ten stages.</h1>
      <p className="mb-6 text-muted">
        703 episodes, from mapping the environment to publishing a package. Each episode groups a message with the tool
        calls that follow it.
      </p>
      <p className="mb-8 text-xs text-muted">
        Stage labels and summaries were generated by Kimi in the original investigation. They sometimes repeat the
        model’s assumptions; read the linked messages to check them.
      </p>
      <nav aria-label="Investigation stages" className="mb-8 border-t border-muted/20">
        {segments.map((s) => (
          <button
            key={s.id}
            type="button"
            onClick={() => chooseStage(s.id)}
            aria-pressed={stage === s.id}
            className={`flex min-h-12 w-full items-baseline gap-3 border-b border-muted/20 py-3 text-left text-sm ${stage === s.id ? "text-primary" : "hover:text-primary"}`}
          >
            <span className="w-5 shrink-0 text-xs tabular-nums text-muted">{String(s.id).padStart(2, "0")}</span>
            <span className="flex-1">{s.label.name}</span>
            <span className="hidden text-xs tabular-nums text-muted sm:block">{s.n_episodes} ep.</span>
            <span aria-hidden="true">↗</span>
          </button>
        ))}
      </nav>
      <label className="block text-sm">
        Search episodes
        <input
          className={`${inputClass} mt-2`}
          type="search"
          value={query}
          placeholder="e.g. email verification"
          onChange={(e) => {
            setQuery(e.target.value);
            setLimit(20);
            setSelected(null);
          }}
        />
      </label>
      <div className="my-4 flex flex-wrap items-center gap-x-5 gap-y-2 text-sm">
        <label className="flex min-h-11 items-center gap-2">
          <input
            className="size-4 accent-primary"
            type="checkbox"
            checked={alarm}
            onChange={(e) => {
              setAlarm(e.target.checked);
              setLimit(20);
              setSelected(null);
            }}
          />
          Self-deception similarity ≥ 0.25
        </label>
        <label className="flex min-h-11 items-center gap-2">
          <input
            className="size-4 accent-primary"
            type="checkbox"
            checked={full}
            onChange={(e) => setFull(e.target.checked)}
          />
          Expand episode text
        </label>
      </div>
      <div className="mb-6 flex flex-wrap items-center justify-between gap-3">
        <output className="text-xs text-muted">
          {filtered.length} / {episodes.length} episodes{stage ? ` · stage ${stage}` : ""}
        </output>
        <button
          className="min-h-11 text-xs text-muted underline"
          type="button"
          onClick={() => {
            chooseStage(0);
            setQuery("");
            setAlarm(false);
          }}
        >
          Show all episodes
        </button>
      </div>
      {segments
        .filter((s) => s.id === stage)
        .map((s) => (
          <section ref={stageRef} key={s.id} className="mb-8 scroll-mt-6 border-l-2 border-primary pl-5">
            <p className="mb-2 text-xs text-muted">
              Stage {s.id} · {s.minutes} minutes · episodes {s.ep_start}–{s.ep_end}
            </p>
            <h2 className="text-xl">{s.label.name}</h2>
            {(Array.isArray(s.label.summary) ? s.label.summary : [s.label.summary]).map((text) => (
              <p key={text} className="mb-3 text-sm">
                {text}
              </p>
            ))}
            <p className="text-sm text-muted">{s.label.handoff}</p>
            <p className="mt-3 flex flex-wrap gap-3 text-xs">
              Milestones:{" "}
              {s.label.milestone_messages.map((n) => (
                <SourceLink key={n} index={n} />
              ))}
            </p>
          </section>
        ))}
      <div className="mb-5 flex gap-3">
        <button type="button" className={`${buttonClass} text-xs`} onClick={() => jumpAlarm(-1)}>
          ← Previous signal
        </button>
        <button type="button" className={`${buttonClass} text-xs`} onClick={() => jumpAlarm(1)}>
          Next signal →
        </button>
      </div>
      {selected !== null ? (
        <section ref={selectedRef} className="mb-8 scroll-mt-6 rounded border border-primary/30 p-4">
          <div className="mb-2 flex justify-between gap-3">
            <p className="text-sm text-primary">Selected episode</p>
            <button
              type="button"
              className="min-h-11 text-xs underline"
              onClick={() => {
                setSelected(null);
                window.history.replaceState(null, "", window.location.pathname);
              }}
            >
              Close
            </button>
          </div>
          {focus ? <EpisodeCard episode={focus} full /> : <p role="alert">This episode is not in the archive.</p>}
        </section>
      ) : null}
      {!filtered.length ? (
        <p className="my-10 text-muted">No episodes match. Try a broader phrase or clear the filters.</p>
      ) : null}
      {filtered.slice(0, limit).map((ep) => (
        <EpisodeCard key={ep.ep} episode={ep} full={full} />
      ))}
      {limit < filtered.length ? (
        <button type="button" className={`${buttonClass} mt-6 w-full`} onClick={() => setLimit((n) => n + 20)}>
          Show 20 more episodes
        </button>
      ) : null}
    </>
  );
}
function EpisodeCard({ episode: ep, full }: { episode: Episode; full: boolean }) {
  return (
    <article className="min-w-0 border-t border-muted/20 py-6">
      <div className="mb-3 flex flex-wrap items-baseline justify-between gap-2">
        <a className={linkClass} href={`#ep${ep.ep}`}>
          Episode {ep.ep}
        </a>
        <p className="text-xs text-muted">
          <SourceLink index={ep.idx_first} />
          {ep.idx_first !== ep.idx_last ? (
            <>
              {" "}
              – <SourceLink index={ep.idx_last} />
            </>
          ) : null}{" "}
          · {ep.ts_start?.slice(11)}
        </p>
      </div>
      {ep.groups.length ? (
        <p className="mb-4 text-[11px] text-primary">{ep.groups.map((g) => g.replaceAll("_", " ")).join(" · ")}</p>
      ) : null}
      {ep.note ? <p className="text-sm text-muted">{ep.note}</p> : null}
      {ep.thinking ? <Expandable label="Thinking" text={ep.thinking} full={full} /> : null}
      {ep.visible ? <Expandable label="Visible text" text={ep.visible} full={full} /> : null}
      {Object.keys(ep.artifacts).length ? (
        <details className="mt-3 text-xs text-muted">
          <summary className="min-h-11 cursor-pointer py-3">Referenced artifacts</summary>
          {Object.entries(ep.artifacts).map(([kind, items]) => (
            <p key={kind} className="mb-2 break-words [overflow-wrap:anywhere]">
              <strong>{kind}: </strong>
              {items.join(" · ")}
            </p>
          ))}
        </details>
      ) : null}
      {ep.tools.length ? (
        <details key={String(full)} open={full} className="mt-3 text-sm">
          <summary className="min-h-11 cursor-pointer py-3 text-muted">{ep.tools.length} tool calls</summary>
          <div className="space-y-5">
            {ep.tools.map((tool) => (
              <div key={tool.idx} className="min-w-0 border-l-2 border-muted/20 pl-4">
                <p className="mb-3 text-xs">
                  <SourceLink index={tool.idx} /> · {tool.name}
                </p>
                <pre className="whitespace-pre-wrap break-words text-xs leading-6 text-muted [overflow-wrap:anywhere]">
                  {tool.call_preview}
                </pre>
                <pre className="mt-3 whitespace-pre-wrap break-words text-xs leading-6 [overflow-wrap:anywhere]">
                  {tool.result_preview}
                </pre>
                <a
                  className={`${linkClass} mt-2 inline-flex min-h-11 items-center text-xs`}
                  href={`/investigation/transcript#m${tool.idx}`}
                >
                  Read full call and result →
                </a>
              </div>
            ))}
          </div>
        </details>
      ) : null}
    </article>
  );
}
function Expandable({ label, text, full }: { label: string; text: string; full: boolean }) {
  const [expanded, setExpanded] = useState(false);
  return (
    <div className="mb-4">
      <p className="mb-2 text-xs uppercase tracking-wide text-muted">{label}</p>
      <p
        className={`whitespace-pre-wrap break-words text-sm leading-7 [overflow-wrap:anywhere] ${full || expanded ? "" : "line-clamp-4"}`}
      >
        {text}
      </p>
      {!full && text.length > 300 ? (
        <button
          type="button"
          className="min-h-11 text-xs text-primary underline"
          onClick={() => setExpanded((v) => !v)}
        >
          {expanded ? "Show less" : "Read more"}
        </button>
      ) : null}
    </div>
  );
}
